// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SplitWiseDB.Data.SplitWise
{
    public partial class BillSplit
    {
        public int Id { get; set; }
        public DateTime? Date { get; set; }
        public string RecipientName { get; set; }
        public string Amount { get; set; }
        public int BillId { get; set; }
        public string UserName { get; set; }
        public string Description { get; set; }
        public string Currency { get; set; }
    }
}