// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SplitWiseDB.Data.SplitWise
{
    public partial class Bill
    {
        public int Id { get; set; }
        public DateTime? Date { get; set; }
        public int? Split { get; set; }
        public string UserName { get; set; }
        public string GroupName { get; set; }
        public double? Amount { get; set; }
        public string Description { get; set; }
        public string Currency { get; set; }
        public int? GroupId { get; set; }
    }
}