// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SplitWiseDB.Data.SplitWise
{
    public partial class FriendsTable
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string FriendName { get; set; }
        public string UserId { get; set; }
        public string FriendId { get; set; }
    }
}