// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SplitWiseDB.Data.SplitWise
{
    public partial class Group
    {
        public int Id { get; set; }
        public DateTime? Date { get; set; }
        public string UserName { get; set; }
        public string GroupName { get; set; }
    }
}